### ISSUE TITLE
How to skip steps based on my previous step content selection?

### ISSUE THREAD

**Issue by SugunRajiv** [forwarder/meteor-wizard-example#1]
Hi recently I started using your wizard and struck at a point where my application needs to skip steps based on previous step content, for example if my first step content is to select a radio button based on selection of radio button I need to go to step one or step two.If radio buttons are male and female in step one and if I select male I need to got step where my male code is written respectively to female content step.I tried to call your next function code twice or thrice to move to respective step that I want but it is not working.Code that I tried..... 

Template.admin_mode1.events({
onSubmit:function(e,template){
e.preventDefault();
if($("#check").val()=="male"){
this.wizard.next();
this.wizard.next();
}
else{
this.wizard.next();
}
}
});

I had other idea in achieving this like if male is selected I want to display male content in next step and similarly if female is selected I want to display female content in next step, but I feel it is difficult because we are writing the whole code in simple schema for each and every step.

 I am struck here and would be great if you solve it for me.

**Comment by Pagebakers** [comment]
Looks like you have setup the onSubmit handler incorrectly. You have to add the onSubmit handler to the step configuration, you can check the documentation to see how to do that.

You can go to a specific step using `this.wizard.show(id)`, this will not validate any steps that you skip and will not save/validate the current step.

``` js
onSubmit:function(data, wizard) {
wizard.setData('current-step-id', data);
// check the gender and pick the next step to show
wizard.show('next-step-id');
}
```

Good luck.

Please note, the planifica wizard is a fork of my version and I have no idea what the state of that package is. If you're using that plugin please 

The support page of my package is located at:
https://github.com/forwarder/meteor-wizard/issues
Please use this address next time you have any issues.

**Comment by SugunRajiv** [comment]
Thanks for your quick reply and I solved it.....LOL...Thank you for such a great package....

**Comment by Pagebakers** [comment]
Cool good job ;), please share your solution so I might help other people to, thanks!
